/**
 * The sphairahedron family's Points sampler — the study's inverse-iteration
 * random walk over the face group, the sphere-inversion family's
 * boundary-sampler role two families over (a present block replaces the
 * chaos game as the cloud's subject, so the explorer needs SOME draw of
 * the set; the limit set is not an IFS attractor and has no chaos game).
 * The decision and its figures are `docs/sphairahedron-family.md`'s
 * "Points stance" measurement: the walk scatters onto the DE's zero set at
 * mean |de| 1.1e-9.
 *
 * SCOPE — FINITE CONSTRUCTIONS. The walk's deep-fold acceptance is
 * measured for the FINITE quasi-spheres (the study's points sheet, and the
 * tests here). An INFINITE construction's limit set is unbounded (the
 * tetra's plane, the terrains), and the walk does not scatter onto it:
 * the face group's action confines a walk point's greedy fold depth to
 * single moves (measured on the infinite tetra: every fold reports 0–4
 * moves and nothing keeps, on either RNG stream), so the cloud draws
 * EMPTY and the panel discloses that a finite construction needs its
 * inversion sphere authored. That is a disclosed gap, not a sampler bug —
 * the study never walked the infinite families.
 *
 * THE WALK. Start at a fixed seed point; one step applies a random FACE's
 * involution — the inversion in a sphere face, or the reflection in a wall
 * plane (the group is generated by ALL the face involutions; the study's
 * walk filtered to spheres because its finite subjects' faces are all
 * spheres under `J` — for the infinite families the walls are planes and
 * the filter would leave a single-generator 2-cycle); keep the current
 * point when its own fold from there is at least
 * {@link SPHAIRAHEDRON_POINTS_MIN_FOLDS} moves deep (the fold's move count
 * is the "distance" to the limit set in moves — points the deep fold
 * cannot improve are already on the set's in-neighborhood). The first
 * {@link SPHAIRAHEDRON_WARMUP} steps are discarded so the seed's transient
 * is gone; the iteration budget is bounded so a measure-zero subject
 * (nothing keeps) draws an EMPTY cloud in bounded time rather than
 * spinning — every budget figure is the study's own walk shape, scaled to
 * the worker's per-request contract. Deterministic in (construction,
 * count, rng) — the chaos game's own reproducibility contract.
 *
 * THE COLOR SLOT is the walk's LAST-APPLIED FACE — "By Transform" wears
 * one hue per fold face, the surface route's per-face slot rule (the
 * hit-info's last-move-face attribution) over the same foldFaces order, so
 * the two consumers cannot disagree about which face owns which hue. The
 * study's DEPTH-color arm stays the surface trap channel
 * (`SPHAIRAHEDRON_TRAP_NORM`); a per-point move count would clamp every
 * accepted point into one slot here (acceptance itself requires ≥ 24
 * moves), so the face, not the depth, is the Points channel — decided,
 * not inherited.
 *
 * THE 4D HALF walks the same loop at n = 4 (the algebra is
 * dimension-free) and hands the points to the standard 4D projection path
 * (the explorer's own rotor + w-ramp machinery) — no slice of its own, the
 * projection being the display; there is no echo to project (the family
 * doc's 4D stance).
 *
 * RESOLUTION PATH: callers hand the CONSTRUCTION (the caller resolves the
 * document). A refused block never reaches here — the cloud request's
 * dispatcher draws nothing for one, except through the morph stance's
 * existence path (`buildSphairahedron`), which is the caller's decision to
 * make, not this module's.
 */
import {
  foldSphairahedron,
  invertPoint,
  makeSphairahedronScratch,
  type SphairahedronConstruction,
  type SphairahedronScratch,
} from "./sphairahedron";
import type { Rng } from "./rng";

/** Apply one face involution to `p` in place — the walk's step: the
 * inversion in a sphere face (`I(x) = c + R²(x−c)/|x−c|²`,
 * `sphairahedron.ts`'s shared `invertPoint`) or the reflection in a wall
 * plane. The face's own sense is already resolved into the construction's
 * `solidInside`/plane orientation, so the fold and the walk read the same
 * generator one layer apart. */
function applyFace(
  face: SphairahedronConstruction["foldFaces"][number]["face"],
  p: number[],
): void {
  if (face.kind === "sphere") {
    const q = invertPoint(face.sphere, p);
    for (let k = 0; k < p.length; k++) p[k] = q[k];
  } else {
    const pl = face.plane;
    let d = -pl.h;
    for (let k = 0; k < p.length; k++) d += pl.n[k] * p[k];
    if (d > 0) {
      for (let k = 0; k < p.length; k++) p[k] -= 2 * d * pl.n[k];
    }
  }
}

/** The most boundary samples one Points cloud draws, whatever the
 * document's point count asks — the menger/sphere-inversion cap class,
 * the same two-seconds-of-worker-time rule (one walk step costs one
 * inversion plus, for candidates, one fold probe). */
export const SPHAIRAHEDRON_POINTS_MAX = 500_000;

/** Minimum fold depth (moves) a kept point's own fold must report — the
 * study's acceptance threshold, measured: at 24 the sampled cloud reads
 * mean |de| 1.1e-9 against the estimator's zero set. */
export const SPHAIRAHEDRON_POINTS_MIN_FOLDS = 24;

/** Walk steps discarded before keeping begins — the study's warm-up. */
export const SPHAIRAHEDRON_WARMUP = 100;

/** Total walk-step budget per draw, beyond the warm-up: 8× the ask (the
 * study's 4× acceptance headroom doubled for the deep-threshold tail)
 * plus a floor so a tiny request still warms up meaningfully. A subject
 * that keeps nothing by then draws empty — the bounded-draw rule. */
function walkBudget(count: number): number {
  return SPHAIRAHEDRON_WARMUP + Math.max(count * 8, 4096);
}

export interface SphairahedronCloud3 {
  count: number;
  positions: Float32Array;
  /** The walk's last-applied face index per point — the color slot. */
  faces: Uint8Array;
}

export interface SphairahedronCloud4 {
  count: number;
  positions: Float32Array;
  /** The fourth coordinate per point, in world w. */
  w: Float32Array;
  /** The walk's last-applied face index per point — the color slot. */
  faces: Uint8Array;
}

/** Sample the construction's limit set by inverse iteration. Deterministic
 * in (construction, count, rng). An empty cloud (count 0) when the
 * construction carries no sphere face to walk or the budget finds no kept
 * point — the caller's gate discloses what that means. */
export function sampleSphairahedronCloud(
  construction: SphairahedronConstruction,
  count: number,
  rng: Rng,
): SphairahedronCloud3 | SphairahedronCloud4 {
  const dim = construction.dim;
  const faceCount = construction.foldFaces.length;
  if (faceCount === 0 || count <= 0) {
    return dim === 4
      ? {
          count: 0,
          positions: new Float32Array(0),
          faces: new Uint8Array(0),
          w: new Float32Array(0),
        }
      : { count: 0, positions: new Float32Array(0), faces: new Uint8Array(0) };
  }
  const cap = Math.min(count, SPHAIRAHEDRON_POINTS_MAX);
  const positions = new Float32Array(cap * 3);
  const w = dim === 4 ? new Float32Array(cap) : null;
  const faces = new Uint8Array(cap);
  const scratch: SphairahedronScratch = makeSphairahedronScratch(dim, 1);
  // The study's seed (0.2, 0.2, 0.2) — the walk's transient is discarded
  // anyway; the value only has to avoid a face centre.
  const p: number[] = new Array<number>(dim).fill(0.2);
  let written = 0;
  const budget = walkBudget(cap);
  for (let i = 0; i < budget && written < cap; i++) {
    const fi = Math.floor(rng() * faceCount);
    applyFace(construction.foldFaces[fi].face, p);
    if (i < SPHAIRAHEDRON_WARMUP) continue;
    // Keep points near the limit set: the fold from here must be deep.
    foldSphairahedron(construction, p, scratch);
    if (scratch.moves < SPHAIRAHEDRON_POINTS_MIN_FOLDS) continue;
    for (let k = 0; k < 3; k++) positions[written * 3 + k] = p[k];
    if (w) w[written] = p[3];
    faces[written] = fi;
    written++;
  }
  if (w) {
    return {
      count: written,
      positions: positions.subarray(0, written * 3),
      w: w.subarray(0, written),
      faces: faces.subarray(0, written),
    };
  }
  return {
    count: written,
    positions: positions.subarray(0, written * 3),
    faces: faces.subarray(0, written),
  };
}
