/**
 * The sphairahedron family's ONE shared vocabulary, imported by both
 * estimator twins (`sphairahedron-de.ts`, `sphairahedron-de-4d.ts`): what a
 * construction IS has one definition across both dimensions, and only the
 * estimators' vector arithmetic is duplicated under the twin-file convention
 * (the `escape-de-4d.ts` rule). The construction, the region derivations and
 * the measurements behind every choice below are in
 * `docs/sphairahedron-family.md`; the pre-gate study's prototype
 * (`scripts/sphairahedron-orbit.ts`) is the independent record this module
 * was transcribed from and checked against.
 *
 * THE OBJECT. A wall system of three planes through the height axis bounds a
 * prism cross-section; excavation balls sit at its corners (Lemma 3.3: the
 * ball is tangent to the vertical corner line at the corner point at the
 * ball's own height, its centre at distance `r` along the wedge-interior
 * direction making the ball's dihedral angles with the wall solid-side
 * normals); radii solve the Lemma 3.5 tangency equations (one per ball pair
 * sharing a wall, LINEAR in the radii — exact elimination, no iteration).
 * The tile is the prism ∧ the divide plane (through the corner vertices)
 * minus the balls; a FINITE sphairahedron is the image of an infinite one
 * under one more inversion sphere `J` (every face maps to a sphere, or to a
 * plane when the face passes through `J`'s centre — handled, not refused).
 * The rendered set is the LIMIT SET Λ = ∂(∪ tiles) of the group generated by
 * the face involutions, rendered through the IIS fold + the accumulated-
 * Jacobian estimate (the estimator twins' module docs).
 *
 * TWO LAYERS, on the `sphere-inversion.ts` precedent:
 *
 *   - AUTHORED ({@link SphairahedronAuthored}): family id × the moduli the
 *     family reads × an optional inversion sphere (absent = the infinite
 *     construction, byte-identically for every document predating it).
 *   - RESOLVED ({@link SphairahedronConstruction}): the explicit fold faces
 *     in scan order, tile pieces, probe, divide, framing ball, seed balls
 *     and verification report the estimators and the analyzer read.
 *
 * {@link resolveSphairahedron} expands the first into the second in the
 * `resolveFoldRadii` style with the disjoint family's deliberate difference:
 * an out-of-region or unknown value is REFUSED with a reason, never clamped,
 * because a clamp would render a different object than the document names.
 * The resolver never mutates or normalizes its input.
 *
 * THE VALID REGION, DERIVED (not copied — the pdftotext extraction of the
 * 2020 preprint mangles coefficients, so every curve below was re-derived
 * from the construction and checked against the appendix's curve list): for
 * the cube families each appendix boundary curve IS one ball's tangency to
 * the wall it does not bound — the ball's sphere crossing that wall is the
 * tile-overlap failure mode, and the tangency is where it degenerates. The
 * thresholds fall out of the placement rule (centre at distance `r` along
 * the corner-to-origin direction; the untouched wall at fixed distance from
 * the corner): type 1 `r = 3/4` (all three balls), type 4 `r = 2√3−3, 4−2√3,
 * 4√3−6` (walls 2, 1, 0), type 9 `r = 1/2, 1/√2, 2√2−2`. Written in the
 * moduli these reproduce the appendix's curves exactly (constants checked:
 * `3zA²+6zA·zB+zB² = 36√3−60`, `15zA²−6zA·zB−zB² = 72√3−120`,
 * `3zA²+6zA·zB−5zB² = 120−72√3` for type 4; `2zA·zB+zB² = 1`,
 * `3zA²−2zA·zB−zB² = 2`, `zB²−zA·zB = 6√2−8` for type 9; `zA·zB = zA²−zA·zB
 * = zB²−zA·zB = 3/4` for type 1). For the prism the appendix's own derivation
 * (Prop 3.12) is the wall-circle fit `ρ < w/2`, which in radii reads
 * `r2 < 1` ⟺ `z2² < 6` — the region is the open interval `(−√6, √6)`. The
 * tetra families have no free moduli and no region. The region is OPEN: a
 * moduli pair ON a threshold still resolves (the construction verifies; the
 * two faces touch tangentially) and the analyzer marks it DEGRADED; past it
 * the resolver refuses with the failing ball named. The panel parameters the
 * owner approved all sit strictly inside (the past-cusp cube-1 sheet was the
 * study's deliberate outside-region rendering, harness-only).
 *
 * THE TWO REFERENCE-CODE DISCREPANCIES the pre-gate study named (CubeE's
 * region condition carries the author's own "It may contain mistake"
 * comment; CubeH's third inequality disagrees with the preprint by one
 * coefficient on zA²) are NOT copied: types 2/3/5/8 are not shipped, and the
 * shipped regions come from the derivation above.
 *
 * THE INVERSION SPHERE. A finite construction needs `J` — a FREE parameter
 * of the family (the quasi-sphere deforms continuously with it, measured in
 * the study), and it is AUTHORED EXPLICITLY: the resolver refuses a finite
 * request without one. There is no silent default, for a measured reason:
 * the reference implementation's constrained sphere (the mirror of the last
 * ball) and even its divide-reflected variant render the COMPLEMENT-POCKET
 * presentation for many parameters (the union is then the unbounded side
 * and the compact blob is too small to frame — the study's j-flip
 * exploration), and the rule that actually produced the owner-approved
 * sheets is the study's deterministic picker, which SAMPLES THE DE SIGN and
 * so cannot live in this pure module. {@link defaultSphairahedronInversion}
 * exposes the reflected-reference rule as the picker's documented FIRST
 * CANDIDATE (an authoring aid for the panel child, which owns the picker);
 * documents carry explicit spheres. A J that degenerates the construction
 * (a seed image that is not a sphere) is refused.
 *
 * PERSISTENCE DESIGN (the wiring lands with the panel/persistence child; the
 * block's contract is decided here): a scene-document block
 * `sphairahedron?: SphairahedronAuthored` on the `sphereInversion` block's
 * precedent — encoded only when present, decoded strictly never-throwing,
 * a refused block carried VERBATIM so a newer document's fields survive an
 * older version's round trip. Unknown keys refuse at RESOLVE time (named),
 * never at decode; absence of the block is the classic transform-system
 * scene byte-identically. The authored fields are exactly
 * {@link SPHAIRAHEDRON_AUTHORED_FIELDS}; every numeric leaf must be finite;
 * values are of any JSON type (an imported document is untrusted) and a
 * wrongly typed value refuses like an out-of-domain one.
 *
 * MORPH STANCE (decided here, wired by the morph child): a morph between two
 * sphairahedron documents of the SAME family lerps the moduli (and, between
 * two finite constructions, the inversion sphere's centre and radius — the
 * quasi-sphere deforms continuously with J, measured in the study) and
 * resolves intermediates through {@link buildSphairahedron}, the
 * construction-existence path, NOT the document resolver — because the valid
 * region is NOT convex (the cube-1 cusp `(√6/4, √6/2)` and its moduli swap
 * are both in-region; their midpoint is not), so a region gate on midpoints
 * would break a legal morph mid-glide. Out-of-region intermediates render
 * coherently (measured: the past-cusp parameters fold with the same
 * statistics, cap never reached). Endpoints are exact: `t = 0/1` resolve to
 * the endpoints' own constructions. Cross-family or infinite↔finite pairs
 * have no meaningful interpolation — the morph is a replace-load, disclosed
 * by the morph driver like any other subject replacement.
 *
 * MUTATION STANCE (decided here, wired by the mutation child): the mutation
 * grid authors no moduli and no family changes — `mutateSystem` preserves
 * the block untouched, wildcard included, on the random-system precedent
 * (it authors no parameters it cannot defend: the region inequalities are
 * exactly what a random nudge cannot guarantee).
 *
 * THE 4D STANCE (the study's, carried forward): the fold, the inversion
 * algebra and the estimators are dimension-free and run at n = 4 unchanged;
 * the shipped 4D family is the tetra lift (the 333 wall hyperplanes, the
 * unit 3-ball at the origin, the tile cut by the invariant hyperplane
 * y = 0), whose limit set is the image of that hyperplane — an analytic
 * 3-sphere once finite. Discreteness for a 4D cell is NOT claimed: the
 * preprint's own 4D classification is open. The slice-then-invert idioms of
 * the disjoint family do NOT transfer here — there is no echo to project; a
 * 4D sphairahedron is its own construction.
 */
// ------------------------------------------------------------- constants

/** The shipped families. The ids name the wall system's corner angles and,
 * for the cubes, the preprint's type number; `tetra4` is the tetra lift one
 * dimension up (the only 4D entry). */
export const SPHAIRAHEDRON_FAMILIES = [
  "tetra333",
  "tetra4",
  "prism2",
  "cube1",
  "cube4",
  "cube9",
] as const;
export type SphairahedronFamilyId = (typeof SPHAIRAHEDRON_FAMILIES)[number];

/** How a query's fold ended — the numeric codes every later mirror
 * dispatches on. */
export const SPHAIRAHEDRON_FOLD_DOMAIN = 0;
/** The pass cap was spent while moves were still being made: the reading is
 * a decision-unreliable value (the cap is a numerical guard, never an
 * object parameter; queries on the limit set never fold in). */
export const SPHAIRAHEDRON_FOLD_CAPPED = 1;
/** The query sat at a face sphere's centre (within
 * {@link SPHAIRAHEDRON_POLE_FLOOR}): the inversion is undefined there.
 * Returns 0, not a member — the sphere-inversion family's pole contract. */
export const SPHAIRAHEDRON_FOLD_POLE = 2;
export type SphairahedronFoldStatus =
  | typeof SPHAIRAHEDRON_FOLD_DOMAIN
  | typeof SPHAIRAHEDRON_FOLD_CAPPED
  | typeof SPHAIRAHEDRON_FOLD_POLE;

/** Relative floor under which a query counts as AT a face sphere's centre:
 * `|x − c| <= floor · r`. */
export const SPHAIRAHEDRON_POLE_FLOOR = 1e-12;

/** The pass cap: the reference implementation's default, a numerical guard
 * against non-terminating scans (queries on the limit set never fold in).
 * Measured fold depths at the surface concentrate at 5–9 moves (peak 7);
 * the cap was never reached at any shipped parameter. */
export const SPHAIRAHEDRON_FOLD_CAP = 50;

/** The estimate's damping factor, measured (the reference ships the same
 * 0.2): the fudge sweep 0.05/0.1/0.2/0.4/0.8 cost 40/26/16/9/4.4 steps/ray
 * at hit rates 80/77/75/74/73% — 0.2 sits at the knee of the cost curve.
 * The march step scale is 1 ({@link SPHAIRAHEDRON_STEP_SCALE}): the fudge
 * IS the damping, exactly the reference's marching arithmetic. */
export const SPHAIRAHEDRON_FUDGE = 0.2;

/** The march step scale: no damping beyond the fudge. */
export const SPHAIRAHEDRON_STEP_SCALE = 1;

/** The depth color source's normalizer: the trap coordinate is
 * `moves / SPHAIRAHEDRON_TRAP_NORM`, clamped — the app ramp's reading of
 * the study's depth-color arm (which cycled a hue per move). The measured
 * surface histogram concentrates at 5–9 moves (peak 7; the cap never
 * reached), so 16 covers the surface range with headroom; a document
 * parameter would make it one (the trap is a color, never geometry). */
export const SPHAIRAHEDRON_TRAP_NORM = 16;

/** A solved radius within `tol · max(1, threshold)` of its region threshold
 * is ON the boundary: admitted, disclosed degraded. */
export const SPHAIRAHEDRON_REGION_BOUNDARY_TOL = 1e-9;

/** Absolute floor under which a solved radius refuses (the tangency system
 * solved to a non-ball). */
export const SPHAIRAHEDRON_MIN_RADIUS = 1e-12;

// ----------------------------------------------------------- authored form

/** The authored compact parametric form (module doc). Every field is
 * optional; the family's own defaults fill what it reads. A field the family
 * does not read is IGNORED, never refused, so switching families keeps the
 * other families' moduli (the sphere-inversion seed-kind rule). An UNKNOWN
 * key is refused ({@link SPHAIRAHEDRON_AUTHORED_FIELDS}). */
export interface SphairahedronAuthored {
  /** A {@link SPHAIRAHEDRON_FAMILIES} id. REQUIRED when the block is
   * present: the family is the subject's identity, and no default family
   * would be honest. */
  family?: string;
  /** Cube families: ball b4's height (the preprint's zA), >= 0. */
  za?: number;
  /** Cube families: ball b6's height (the preprint's zB), >= 0. */
  zb?: number;
  /** Prism family: the first ball's height; the valid region is the open
   * interval (−√6, √6). */
  z2?: number;
  /** Finite type: the inversion sphere. Absent = the INFINITE construction
   * (byte-identically for every document predating finite authoring);
   * present = finite, with the centre (cx, cy, cz[, cw]) and radius r
   * AUTHORED EXPLICITLY — the sphere is a free parameter of the family and
   * the resolver refuses a finite request without one (module doc). `cw` is
   * the centre's w — 4D families only; a nonzero value on a 3D family is
   * refused. */
  inversion?: {
    cx?: number;
    cy?: number;
    cz?: number;
    cw?: number;
    r?: number;
  };
}

/** Every field the authored form defines. Any other key is REFUSED as
 * unknown: a document written by a newer version may name a field this
 * version cannot read, and ignoring it would render a different object than
 * the document names (the no-clamp rule applied to keys). */
export const SPHAIRAHEDRON_AUTHORED_FIELDS: readonly string[] = Object.freeze([
  "family",
  "za",
  "zb",
  "z2",
  "inversion",
]);
export const SPHAIRAHEDRON_INVERSION_FIELDS: readonly string[] = Object.freeze([
  "cx",
  "cy",
  "cz",
  "cw",
  "r",
]);

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v);
}

// ------------------------------------------------------------- geometry

/** Half-space boundary `n·p = h`; the REMOVED side is `n·p > h` (the fold
 * reflects across it, the tile excludes it). */
export interface SphairahedronPlane {
  n: readonly number[];
  h: number;
}

export type SphairahedronSphere = { c: readonly number[]; r: number };

export type SphairahedronFace =
  | { kind: "sphere"; sphere: SphairahedronSphere }
  | { kind: "plane"; plane: SphairahedronPlane };

/** One fold generator in SCAN ORDER with its sense: a face whose solid side
 * is the sphere's INTERIOR folds points that are OUTSIDE it (`d² > r²`),
 * not inside — getting this wrong silently folds points out of the tile and
 * renders garbage (the study's flagged defect). */
export interface SphairahedronFoldFace {
  face: SphairahedronFace;
  solidInside: boolean;
}

/** One max-form term of a tile piece; the solid is where the SDF <= 0.
 * Sphere: `inside` = the solid includes the ball's interior (SDF
 * `dist − r`), else the solid excludes it (SDF `r − dist`). Plane: `above`
 * = the solid side is `n·p > h` (SDF `h − n·p`), else `n·p < h`
 * (SDF `n·p − h`). */
export type SphairahedronTerm =
  | { kind: "sphere"; c: readonly number[]; r: number; inside: boolean }
  | { kind: "plane"; n: readonly number[]; h: number; above: boolean };

export interface SphairahedronTilePiece {
  terms: readonly SphairahedronTerm[];
}

/** A maximum vertex ball (the preprint's Def 4.1 seeds): the ball through a
 * vertex, orthogonal to every edge there, maximal along its centre line, on
 * the side that pokes into the tile. */
export interface SphairahedronSeedBall {
  c: readonly number[];
  r: number;
}

/** A construction vertex: its point and the combined face indices (balls
 * first, then walls) it joins. The finite construction carries the images. */
export interface SphairahedronVertex {
  p: readonly number[];
  faces: readonly number[];
}

export interface SphairahedronVerification {
  /** Lemma 3.3(2): |centre − corner| − r, and the Lemma 3.5 wall-circle
   * gap at the feet. */
  maxTangentErr: number;
  /** Lemma 3.3(3) as the plane/sphere dihedral: |acos(δ/r) − θ|. */
  maxAngleErr: number;
  /** Non-fatal construction notes (extra crossings live on the report's
   * `crossings`, not here). */
  problems: string[];
  /** Walls each ball crosses beyond its corner pair, by ball name. */
  crossings: Readonly<Record<string, readonly number[]>>;
}

/** The explicit construction every estimator and the analyzer read. */
export interface SphairahedronConstruction {
  dim: 3 | 4;
  family: SphairahedronFamilyId;
  /** The moduli the family reads, defaults filled (za/zb for the cubes,
   * z2 for the prism; the tetra families carry none). */
  moduli: { za?: number; zb?: number; z2?: number };
  /** False for the infinite construction; true once mapped through `J`. */
  finite: boolean;
  /** The finite type's inversion sphere (null when infinite). */
  inversion: { c: readonly number[]; r: number } | null;
  /** Fold generators in SCAN ORDER: balls then walls for the infinite
   * types; the reference's interleaved wall/ball order for finite ones.
   * Scan order is PART of the algorithm once faces intersect. */
  foldFaces: readonly SphairahedronFoldFace[];
  /** The tile's max-form pieces (the prism ∧ divide minus the balls; the
   * prism family's second piece rides its own divide side). */
  pieces: readonly SphairahedronTilePiece[];
  /** A point strictly inside the fundamental tile. */
  probe: readonly number[];
  /** The tile's divide plane — the quasi-sphere's smooth carrier. */
  divide: SphairahedronPlane;
  /** Framing: finite scenes, the convex sphere; infinite ones, a generous
   * ball the caller turns into a march interval. */
  bound: { center: readonly number[]; radius: number };
  /** Maximum vertex balls (empty for the tetra families: their vertex
   * balls degenerate to half-spaces). */
  seeds: readonly SphairahedronSeedBall[];
  /** The construction's vertices (finite: their images under `J`), each
   * with the combined face indices it joins. */
  vertices: readonly SphairahedronVertex[];
  foldCap: number;
  /** The solved radii, ball order (b2, b4, b6 / b, b4). */
  radii: readonly number[];
  /** The solved ball centres, same order. */
  ballCenters: readonly (readonly number[])[];
  verification: SphairahedronVerification;
  /** A moduli pair ON a region threshold (admitted, disclosed degraded by
   * the analyzer). */
  regionBoundary: boolean;
}

// --------------------------------------------------------- wall systems

interface WallLine {
  /** 2D unit normal of the cross-section line, pointing to the REMOVED
   * side; the wall hyperplane lifts it to (a0, 0, a1, 0…). */
  a: [number, number];
  h: number;
}

interface WallCorner {
  i: number;
  j: number;
  q: [number, number];
  angle: number;
}

interface WallSystem {
  lines: WallLine[];
  corners: WallCorner[];
  /** Per wall: the distance between its two corners (Lemma 3.5's w). */
  width: number[];
}

const RT3 = Math.sqrt(3);
const RT2 = Math.SQRT2;

function widths(corners: WallCorner[]): number[] {
  const d = (p: [number, number], q: [number, number]) =>
    Math.hypot(p[0] - q[0], p[1] - q[1]);
  return [
    d(corners[0].q, corners[1].q),
    d(corners[0].q, corners[2].q),
    d(corners[1].q, corners[2].q),
  ];
}

/** The equilateral system: removed sides x·½ ± √3z/2 ≥ h, −x ≥ h. Corner
 * angles π/3; corner(0,1) = (2h, 0), corner(0,2) = (−h, √3h), corner(1,2) =
 * (−h, −√3h). `h` is the inradius. */
function wallSystem333(h: number): WallSystem {
  const corners: WallCorner[] = [
    { i: 0, j: 1, q: [2 * h, 0], angle: Math.PI / 3 },
    { i: 0, j: 2, q: [-h, RT3 * h], angle: Math.PI / 3 },
    { i: 1, j: 2, q: [-h, -RT3 * h], angle: Math.PI / 3 },
  ];
  return {
    lines: [
      { a: [0.5, RT3 / 2], h },
      { a: [0.5, -RT3 / 2], h },
      { a: [-1, 0], h },
    ],
    corners,
    width: widths(corners),
  };
}

/** (π/2, π/3, π/6) at corners (0,1), (0,2), (1,2). */
function wallSystem236(): WallSystem {
  const corners: WallCorner[] = [
    { i: 0, j: 1, q: [1, 0], angle: Math.PI / 2 },
    { i: 0, j: 2, q: [0.5, RT3 / 2], angle: Math.PI / 3 },
    { i: 1, j: 2, q: [-0.5, -RT3 / 2], angle: Math.PI / 6 },
  ];
  return {
    lines: [
      { a: [RT3 / 2, 0.5], h: RT3 / 2 },
      { a: [0.5, -RT3 / 2], h: 0.5 },
      { a: [-RT3 / 2, 0.5], h: 0 },
    ],
    corners,
    width: widths(corners),
  };
}

/** (π/2, π/4, π/4) at corners (0,1), (0,2), (1,2). */
function wallSystem244(): WallSystem {
  const corners: WallCorner[] = [
    { i: 0, j: 1, q: [1, 0], angle: Math.PI / 2 },
    { i: 0, j: 2, q: [0, 1], angle: Math.PI / 4 },
    { i: 1, j: 2, q: [0, -1], angle: Math.PI / 4 },
  ];
  return {
    lines: [
      { a: [1 / RT2, 1 / RT2], h: 1 / RT2 },
      { a: [1 / RT2, -1 / RT2], h: 1 / RT2 },
      { a: [-1, 0], h: 0 },
    ],
    corners,
    width: widths(corners),
  };
}

/** The wall hyperplane in n dims: cross-section normal lifted; the height
 * axis (index 1) and any extra axis (index 3) untouched. */
function wallPlane(line: WallLine, dim: 3 | 4): SphairahedronPlane {
  const n = new Array<number>(dim).fill(0);
  n[0] = line.a[0];
  n[2] = line.a[1];
  return { n, h: line.h };
}

// --------------------------------------------------------- ball solving

interface BallSpec {
  /** The two walls meeting at this ball's ideal vertex. */
  corner: [number, number];
  /** Absolute height of the vertex (and centre). */
  height: number;
  /** Dihedral angle to wall `corner[0]`, then to wall `corner[1]`. */
  theta: [number, number];
  /** Pinned radius; absent, the tangency system solves for it. */
  radius?: number;
  name: string;
}

function dot(a: ArrayLike<number>, b: ArrayLike<number>): number {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += a[i] * b[i];
  return s;
}

function dist(a: ArrayLike<number>, b: ArrayLike<number>): number {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += (a[i] - b[i]) ** 2;
  return Math.sqrt(s);
}

function cross3(a: number[], b: number[]): number[] {
  return [
    a[1] * b[2] - a[2] * b[1],
    a[2] * b[0] - a[0] * b[2],
    a[0] * b[1] - a[1] * b[0],
  ];
}

/** Unit direction from the corner making angle theta[0] with wall
 * corner[0]'s solid normal and theta[1] with the other's — the unique
 * direction inside the solid wedge (Lemma 3.3(3), solid-side reading).
 * Throws when the two angles do not close the vertex (θa + θb + θab = π). */
function ballDirection(ws: WallSystem, spec: BallSpec): [number, number] {
  const [i, j] = spec.corner;
  const si: [number, number] = [-ws.lines[i].a[0], -ws.lines[i].a[1]];
  const sj: [number, number] = [-ws.lines[j].a[0], -ws.lines[j].a[1]];
  const proj = sj[0] * si[0] + sj[1] * si[1];
  let t: [number, number] = [sj[0] - proj * si[0], sj[1] - proj * si[1]];
  const tl = Math.hypot(t[0], t[1]);
  t = [t[0] / tl, t[1] / tl];
  const cosT = Math.cos(spec.theta[0]);
  const sinT = Math.sin(spec.theta[0]);
  const u: [number, number] = [
    si[0] * cosT + t[0] * sinT,
    si[1] * cosT + t[1] * sinT,
  ];
  const aJ = Math.acos(Math.max(-1, Math.min(1, u[0] * sj[0] + u[1] * sj[1])));
  if (Math.abs(aJ - spec.theta[1]) > 1e-9) {
    throw new Error(
      `ball ${spec.name}: direction angles (${spec.theta[0]}, ${aJ}) do ` +
        `not close the vertex`,
    );
  }
  return u;
}

/**
 * Solve the Lemma 3.5 tangency system for the radii. One equation per ball
 * pair sharing a wall:
 *   r1·sin θ1w + r2·sin θ2w = (w² + Δh²) / (2w),
 * linear in the unpinned radii; pinned ones substitute. Exact elimination,
 * no iteration. Throws when the equations and unknowns mismatch or the
 * system is singular.
 */
function solveBalls(
  ws: WallSystem,
  specs: BallSpec[],
  dim: 3 | 4,
): { radii: number[]; centers: number[][] } {
  const dirs = specs.map((s) => ballDirection(ws, s));
  const unpinned = specs.map((s) => s.radius === undefined);
  const unknowns = unpinned.filter(Boolean).length;
  const eqs: { a: number; b: number; w: number; rhs: number }[] = [];
  for (let a = 0; a < specs.length; a++) {
    for (let b = a + 1; b < specs.length; b++) {
      const shared = specs[a].corner.filter((w) => specs[b].corner.includes(w));
      if (shared.length !== 1) continue;
      const w = shared[0];
      const ww = ws.width[w];
      const dh = specs[a].height - specs[b].height;
      eqs.push({ a, b, w, rhs: (ww * ww + dh * dh) / (2 * ww) });
    }
  }
  if (eqs.length !== unknowns) {
    throw new Error(
      `tangency system has ${eqs.length} equations for ${unknowns} unknowns`,
    );
  }
  const col = new Map<number, number>();
  let next = 0;
  for (let i = 0; i < specs.length; i++) if (unpinned[i]) col.set(i, next++);
  const sinOf = (i: number, w: number) =>
    Math.sin(specs[i].theta[specs[i].corner.indexOf(w)]);
  const m: number[][] = eqs.map((e) => {
    const row = new Array<number>(unknowns + 1).fill(0);
    const ra = specs[e.a].radius;
    const rb = specs[e.b].radius;
    if (unpinned[e.a]) row[col.get(e.a) as number] += sinOf(e.a, e.w);
    else if (ra !== undefined) row[unknowns] -= ra * sinOf(e.a, e.w);
    if (unpinned[e.b]) row[col.get(e.b) as number] += sinOf(e.b, e.w);
    else if (rb !== undefined) row[unknowns] -= rb * sinOf(e.b, e.w);
    row[unknowns] += e.rhs;
    return row;
  });
  for (let i = 0; i < unknowns; i++) {
    let piv = i;
    for (let r = i + 1; r < m.length; r++)
      if (Math.abs(m[r][i]) > Math.abs(m[piv][i])) piv = r;
    [m[i], m[piv]] = [m[piv], m[i]];
    if (Math.abs(m[i][i]) < 1e-12)
      throw new Error("tangency system is singular");
    for (let r = 0; r < m.length; r++) {
      if (r === i) continue;
      const f = m[r][i] / m[i][i];
      for (let c = i; c <= unknowns; c++) m[r][c] -= f * m[i][c];
    }
  }
  const radii = specs.map((s, i) =>
    s.radius !== undefined
      ? s.radius
      : m[col.get(i) as number][unknowns] / m[col.get(i) as number][i],
  );
  const centers = specs.map((s, i) => {
    const corner = ws.corners.find(
      (c) => c.i === s.corner[0] && c.j === s.corner[1],
    );
    if (!corner) throw new Error(`no corner for ball ${s.name}`);
    const c = new Array<number>(dim).fill(0);
    c[0] = corner.q[0] + radii[i] * dirs[i][0];
    c[1] = s.height;
    c[2] = corner.q[1] + radii[i] * dirs[i][1];
    return c;
  });
  return { radii, centers };
}

// -------------------------------------------------------------- inversion

/** The inversion `I(x) = c + R²(x−c)/|x−c|²` in the sphere `j`. */
function invertPoint(j: SphairahedronSphere, p: readonly number[]): number[] {
  const d2 = dist(p, j.c) ** 2;
  const k = (j.r * j.r) / d2;
  return j.c.map((v, i) => v + k * (p[i] - v));
}

type HImage =
  | { kind: "sphere"; sphere: SphairahedronSphere }
  | { kind: "plane"; plane: SphairahedronPlane };

/** Image of a sphere: a sphere, or a plane when the surface passes through
 * the inversion centre. */
function invertSphere(j: SphairahedronSphere, s: SphairahedronSphere): HImage {
  const dc: number[] = s.c.map((v, i) => v - j.c[i]);
  const d2 = dot(dc, dc);
  const den = d2 - s.r * s.r;
  if (Math.abs(den) < 1e-9 * Math.max(1, d2)) {
    const len = Math.sqrt(d2);
    const n = dc.map((v) => v / len);
    return {
      kind: "plane",
      plane: { n, h: dot(j.c, n) + (j.r * j.r) / (2 * len) },
    };
  }
  const k = (j.r * j.r) / den;
  return {
    kind: "sphere",
    sphere: { c: j.c.map((v, i) => v + k * dc[i]), r: Math.abs(k) * s.r },
  };
}

/** Image of a plane: a sphere through the inversion centre, or the plane
 * itself when the centre lies on it. */
function invertPlane(j: SphairahedronSphere, pl: SphairahedronPlane): HImage {
  const d = dot(pl.n, j.c) - pl.h;
  if (Math.abs(d) < 1e-12 * Math.max(1, j.r)) {
    return { kind: "plane", plane: { n: [...pl.n], h: pl.h } };
  }
  const k = (j.r * j.r) / (2 * d);
  return {
    kind: "sphere",
    sphere: { c: j.c.map((v, i) => v - k * pl.n[i]), r: Math.abs(k) },
  };
}

// -------------------------------------------------------------- the tile

function termSDF(t: SphairahedronTerm, p: ArrayLike<number>): number {
  if (t.kind === "sphere") {
    const d = dist(p, t.c) - t.r;
    return t.inside ? d : -d;
  }
  const d = dot(t.n, p) - t.h;
  return t.above ? -d : d;
}

/** The tile SDF: max-form intersection per piece, min over pieces.
 * Negative inside the union of tiles, positive outside — the reference
 * implementation's exact convention. */
export function sphairahedronTileSDF(
  construction: SphairahedronConstruction,
  p: ArrayLike<number>,
): number {
  let best = Infinity;
  for (const piece of construction.pieces) {
    let d = -Infinity;
    for (const t of piece.terms) {
      const v = termSDF(t, p);
      if (v > d) d = v;
    }
    if (d < best) best = d;
  }
  return best;
}

// ------------------------------------------------------------- the fold

/** Scratch for the fold: the folded point, the accumulated conformal
 * Jacobian and the move counters. Reused across calls; no allocations in
 * the hot path. `lastFace` is the fold's last-move face index (−1 when it
 * never moved) — the per-face color attribution both readings carry. */
export interface SphairahedronScratch {
  x: Float64Array;
  moves: number;
  inversions: number;
  reflections: number;
  passes: number;
  capped: boolean;
  skippedPole: boolean;
  lambda: number;
  lastFace: number;
}

export function makeSphairahedronScratch(
  dim: 3 | 4,
  _cap: number,
): SphairahedronScratch {
  return {
    x: new Float64Array(dim),
    moves: 0,
    inversions: 0,
    reflections: 0,
    passes: 0,
    capped: false,
    skippedPole: false,
    lambda: 1,
    lastFace: -1,
  };
}

/**
 * The IIS fold (the estimator twins run this through their flattened
 * tables; this plain-data form is the vocabulary's own reading and the
 * tests' cross-check): per pass, scan the faces in order; a face sphere
 * holding the point on its REMOVED side inverts it (λ ×= R²/|p−c|²), a
 * violated wall reflects it (λ unchanged); the scan CONTINUES within the
 * pass and passes repeat until a clean one or the cap. The cap is a
 * numerical guard, not an object parameter — queries on the limit set
 * never fold in.
 */
export function foldSphairahedron(
  construction: SphairahedronConstruction,
  p: ArrayLike<number>,
  s: SphairahedronScratch,
): SphairahedronScratch {
  const dim = construction.dim;
  for (let i = 0; i < dim; i++) s.x[i] = p[i];
  s.moves = 0;
  s.inversions = 0;
  s.reflections = 0;
  s.passes = 0;
  s.capped = false;
  s.skippedPole = false;
  s.lambda = 1;
  s.lastFace = -1;
  for (;;) {
    let moved = false;
    for (
      let faceIndex = 0;
      faceIndex < construction.foldFaces.length;
      faceIndex++
    ) {
      const { face, solidInside } = construction.foldFaces[faceIndex];
      if (face.kind === "sphere") {
        const c = face.sphere.c;
        const r = face.sphere.r;
        let d2 = 0;
        for (let i = 0; i < dim; i++) {
          const t = s.x[i] - c[i];
          d2 += t * t;
        }
        const onRemovedSide = solidInside ? d2 > r * r : d2 < r * r;
        if (onRemovedSide) {
          if (
            d2 <
            SPHAIRAHEDRON_POLE_FLOOR * SPHAIRAHEDRON_POLE_FLOOR * r * r
          ) {
            s.skippedPole = true;
            continue;
          }
          const k = (r * r) / d2;
          for (let i = 0; i < dim; i++) s.x[i] = c[i] + k * (s.x[i] - c[i]);
          s.lambda *= k;
          s.inversions++;
          s.moves++;
          s.lastFace = faceIndex;
          moved = true;
        }
      } else {
        const pl = face.plane;
        let d = -pl.h;
        for (let i = 0; i < dim; i++) d += pl.n[i] * s.x[i];
        if (d > 0) {
          for (let i = 0; i < dim; i++) s.x[i] -= 2 * d * pl.n[i];
          s.reflections++;
          s.moves++;
          s.lastFace = faceIndex;
          moved = true;
        }
      }
    }
    s.passes++;
    if (!moved) break;
    if (s.passes >= construction.foldCap) {
      s.capped = true;
      break;
    }
  }
  return s;
}

/** Membership in the union of tiles: the fold terminates within the cap AND
 * the folded point satisfies the tile's own conditions (the fold does not
 * test the divide plane, so termination alone is weaker). A skipped pole is
 * not a member. */
export function sphairahedronContains(
  construction: SphairahedronConstruction,
  p: ArrayLike<number>,
  s: SphairahedronScratch,
): boolean {
  foldSphairahedron(construction, p, s);
  if (s.skippedPole) return false;
  return !s.capped && sphairahedronTileSDF(construction, s.x) <= 0;
}

// ------------------------------------------------------- the construction

interface BuildOptions {
  dim: 3 | 4;
  ws: WallSystem;
  balls: BallSpec[];
  /** Explicit divide hyperplane; absent, the plane through the corner
   * vertices. */
  divide?: SphairahedronPlane;
}

/** The built infinite scene: the construction's geometry plus the combined
 * face list and vertices the finite mapping and the seeds read. */
interface BuiltScene {
  dim: 3 | 4;
  foldFaces: SphairahedronFoldFace[];
  pieces: SphairahedronTilePiece[];
  /** Combined face list for the finite mapping: balls then walls. */
  faces: SphairahedronFace[];
  vertices: { p: number[]; faces: number[] }[];
  probe: number[];
  divide: SphairahedronPlane;
  bound: { center: number[]; radius: number };
  seeds: SphairahedronSeedBall[];
  foldCap: number;
  radii: number[];
  ballCenters: number[][];
  verification: SphairahedronVerification;
}

/** Assemble the infinite sphairahedron: solve the radii, verify Lemmas
 * 3.3/3.5 numerically, build the vertices, the divide plane, the tile and
 * the maximum vertex balls. Throws on a construction that cannot be built
 * (singular tangency system, no divide plane); verification problems are
 * REPORTED, not thrown — the analyzer turns them into reasons. */
function buildInfinite(opts: BuildOptions): { scene: BuiltScene } {
  const { dim, ws, balls } = opts;
  const { radii, centers } = solveBalls(ws, balls, dim);
  const ballCount = radii.length;
  const problems: string[] = [];
  let maxTangentErr = 0;
  let maxAngleErr = 0;
  const extraCrossings: Record<string, number[]> = {};

  // Lemma 3.3(2): the ball is tangent to its corner line; 3.3(3) read as
  // the plane/sphere dihedral: cos θ = δ/r.
  balls.forEach((spec, i) => {
    const corner = ws.corners.find(
      (c) => c.i === spec.corner[0] && c.j === spec.corner[1],
    ) as WallCorner;
    const d = Math.hypot(
      centers[i][0] - corner.q[0],
      centers[i][2] - corner.q[1],
    );
    maxTangentErr = Math.max(maxTangentErr, Math.abs(d - radii[i]));
    if (radii[i] <= 0)
      problems.push(`ball ${spec.name}: radius ${radii[i]} <= 0`);
    spec.corner.forEach((w, k) => {
      const pl = wallPlane(ws.lines[w], dim);
      const delta = Math.abs(dot(pl.n, centers[i]) - pl.h);
      const angle = Math.acos(Math.max(-1, Math.min(1, delta / radii[i])));
      maxAngleErr = Math.max(maxAngleErr, Math.abs(angle - spec.theta[k]));
    });
    // Any wall the ball additionally crosses is reported (the prism's
    // second vertex lives on one).
    const extra: number[] = [];
    for (let w = 0; w < ws.lines.length; w++) {
      if (spec.corner.includes(w)) continue;
      const pl = wallPlane(ws.lines[w], dim);
      const delta = Math.abs(dot(pl.n, centers[i]) - pl.h);
      if (delta < radii[i] * (1 - 1e-12)) extra.push(w);
    }
    if (extra.length > 0) extraCrossings[spec.name] = extra;
  });

  // Vertices: each ball's corner vertex, plus any extra corner-line
  // contacts (the prism family's second vertex lives on one).
  const vertices: { p: number[]; faces: number[] }[] = [];
  balls.forEach((spec, i) => {
    const corner = ws.corners.find(
      (c) => c.i === spec.corner[0] && c.j === spec.corner[1],
    ) as WallCorner;
    const p = new Array<number>(dim).fill(0);
    p[0] = corner.q[0];
    p[1] = spec.height;
    p[2] = corner.q[1];
    vertices.push({
      p,
      faces: [i, ballCount + spec.corner[0], ballCount + spec.corner[1]],
    });
    for (const w of extraCrossings[spec.name] ?? []) {
      for (const cc of ws.corners.filter((c) => c.i === w || c.j === w)) {
        const d = Math.hypot(centers[i][0] - cc.q[0], centers[i][2] - cc.q[1]);
        if (Math.abs(d - radii[i]) <= 1e-9 * Math.max(1, radii[i])) {
          const p2 = new Array<number>(dim).fill(0);
          p2[0] = cc.q[0];
          p2[1] = spec.height;
          p2[2] = cc.q[1];
          vertices.push({
            p: p2,
            faces: [i, ballCount + cc.i, ballCount + cc.j],
          });
        }
      }
    }
  });

  // Lemma 3.5: tangency of the wall circles per sharing pair. The circles
  // live in the wall plane with centres at the feet of the ball centres.
  const foot = (i: number, pl: SphairahedronPlane): number[] => {
    const d = dot(pl.n, centers[i]) - pl.h;
    return centers[i].map((v, k) => v - d * pl.n[k]);
  };
  for (let a = 0; a < balls.length; a++) {
    for (let b = a + 1; b < balls.length; b++) {
      const shared = balls[a].corner.find((w) => balls[b].corner.includes(w));
      if (shared === undefined) continue;
      const pl = wallPlane(ws.lines[shared], dim);
      const ra = Math.sqrt(
        Math.max(0, radii[a] ** 2 - dist(centers[a], foot(a, pl)) ** 2),
      );
      const rb = Math.sqrt(
        Math.max(0, radii[b] ** 2 - dist(centers[b], foot(b, pl)) ** 2),
      );
      const gap = dist(foot(a, pl), foot(b, pl)) - (ra + rb);
      maxTangentErr = Math.max(maxTangentErr, Math.abs(gap));
      if (Math.abs(gap) > 1e-7 * Math.max(1, ra + rb)) {
        problems.push(
          `balls ${balls[a].name}/${balls[b].name}: wall circles not tangent ` +
            `(gap ${gap.toExponential(2)})`,
        );
        continue;
      }
      const fa = foot(a, pl);
      const fb = foot(b, pl);
      const t = ra / (ra + rb);
      vertices.push({
        p: fa.map((v, i) => v + t * (fb[i] - v)),
        faces: [a, b, ballCount + shared],
      });
    }
  }

  // The three-ball vertex: the balls' common point where their pairwise
  // circles are mutually tangent (P246 for the cube).
  if (balls.length === 3) {
    const triple = tripleBallVertex(centers, radii);
    if (triple) vertices.push({ p: triple, faces: [0, 1, 2] });
    else problems.push("no common point of the three balls (P246 missing)");
  }

  // The divide plane.
  let divide: SphairahedronPlane | undefined = opts.divide;
  if (!divide) {
    const pts = vertices.filter((v) => v.faces.length === 3);
    if (pts.length < 3)
      throw new Error("need three corner vertices for the divide plane");
    divide = planeThrough3(pts[0].p, pts[1].p, pts[2].p, dim);
  }

  // Tile pieces.
  const terms: SphairahedronTerm[] = [
    ...ws.lines.map((l): SphairahedronTerm => ({
      kind: "plane",
      n: wallPlane(l, dim).n,
      h: l.h,
      above: false,
    })),
    ...radii.map((r, i): SphairahedronTerm => ({
      kind: "sphere",
      c: centers[i],
      r,
      inside: false,
    })),
  ];
  const probe = new Array<number>(dim).fill(0);
  probe[1] = Math.min(...balls.map((b) => b.height)) - 2;
  // Orient the divide's solid side by the probe.
  const dVal = dot(divide.n, probe) - divide.h;
  terms.push({
    kind: "plane",
    n: [...divide.n],
    h: divide.h,
    above: dVal > 0,
  });
  const pieces: SphairahedronTilePiece[] = [{ terms }];

  const faces: SphairahedronFace[] = [
    ...radii.map((r, i) => ({
      kind: "sphere" as const,
      sphere: { c: centers[i], r },
    })),
    ...ws.lines.map((l) => ({
      kind: "plane" as const,
      plane: wallPlane(l, dim),
    })),
  ];
  const scene = {
    dim,
    foldFaces: [
      ...radii.map((r, i) => ({
        face: {
          kind: "sphere" as const,
          sphere: { c: centers[i], r },
        },
        solidInside: false,
      })),
      ...ws.lines.map((l) => ({
        face: {
          kind: "plane" as const,
          plane: wallPlane(l, dim),
        },
        solidInside: false,
      })),
    ],
    pieces,
    faces,
    vertices,
    probe,
    divide,
    bound: frameBound(dim, balls, radii, centers),
    seeds: maxVertexBalls(faces, vertices, pieces),
    foldCap: SPHAIRAHEDRON_FOLD_CAP,
    radii,
    ballCenters: centers,
    verification: {
      maxTangentErr,
      maxAngleErr,
      problems,
      crossings: extraCrossings,
    },
  };
  return { scene };
}

/** One of the two common points of three spheres, chosen where their
 * pairwise circles are mutually tangent; null when they have no common
 * point or are not mutually tangent at either. Can degenerate to a
 * TANGENCY (disc ≈ 0⁻ — clamped, not rejected). */
function tripleBallVertex(
  centers: number[][],
  radii: number[],
): number[] | null {
  const [c0, c1, c2] = centers;
  const [r0, r1, r2] = radii;
  const l1 = c1.map((v, i) => 2 * (v - c0[i]));
  const l2 = c2.map((v, i) => 2 * (v - c0[i]));
  const k1 = dot(c1, c1) - r1 * r1 - (dot(c0, c0) - r0 * r0);
  const k2 = dot(c2, c2) - r2 * r2 - (dot(c0, c0) - r0 * r0);
  // Closest point to c0 on the radical line: p* = c0 + Lᵀ(LLᵀ)⁻¹(k − Lc0);
  // the tangent circles touch at p* ± √(r0² − |p*−c0|²) along the line.
  const dim = c0.length;
  const a00 = dot(l1, l1);
  const a01 = dot(l1, l2);
  const a11 = dot(l2, l2);
  const det = a00 * a11 - a01 * a01;
  if (Math.abs(det) < 1e-30) return null;
  const r1v = k1 - dot(l1, c0);
  const r2v = k2 - dot(l2, c0);
  const wa = (a11 * r1v - a01 * r2v) / det;
  const wb = (a00 * r2v - a01 * r1v) / det;
  const pStar = c0.map((v, i) => v + wa * l1[i] + wb * l2[i]);
  if (dim !== 3) return null;
  const dir = cross3(l1, l2);
  const dl = dot(dir, dir);
  if (dl < 1e-30) return null;
  const gap = dist(pStar, c0);
  let disc = r0 * r0 - gap * gap;
  if (disc < 0) {
    if (disc < -1e-9 * r0 * r0) return null;
    disc = 0;
  }
  const t = Math.sqrt(disc) / dl;
  const parallel = (p: number[]): number => {
    const t01 = cross3(
      p.map((v, i) => v - c0[i]),
      p.map((v, i) => v - c1[i]),
    );
    const t02 = cross3(
      p.map((v, i) => v - c0[i]),
      p.map((v, i) => v - c2[i]),
    );
    const t12 = cross3(
      p.map((v, i) => v - c1[i]),
      p.map((v, i) => v - c2[i]),
    );
    const u = Math.hypot(...t01);
    if (u < 1e-15) return Infinity;
    const n01 = t01.map((v) => v / u);
    const n02 = t02.map((v) => v / (Math.hypot(...t02) || 1));
    const n12 = t12.map((v) => v / (Math.hypot(...t12) || 1));
    return Math.max(1 - Math.abs(dot(n01, n02)), 1 - Math.abs(dot(n01, n12)));
  };
  const pPlus = dir.map((v, i) => pStar[i] + t * v);
  const pMinus = dir.map((v, i) => pStar[i] - t * v);
  const ePlus = parallel(pPlus);
  const eMinus = parallel(pMinus);
  if (Math.min(ePlus, eMinus) > 1e-6) return null;
  return ePlus <= eMinus ? pPlus : pMinus;
}

function planeThrough3(
  a: number[],
  b: number[],
  c: number[],
  dim: 3 | 4,
): SphairahedronPlane {
  const n = cross3(
    b.map((v, i) => v - a[i]),
    c.map((v, i) => v - a[i]),
  );
  const l = Math.hypot(...n);
  const u = n.map((v) => v / l);
  if (dim === 4) {
    // The 3D cross product of the two difference vectors lies in the
    // hyperplane spanned by them; for axis-aligned constructions the
    // normal needs no w component — refuse rather than guess.
    if (Math.abs(u[3]) > 1e-9)
      throw new Error("divide plane needs a w component; pass it explicitly");
    u.pop();
  }
  return { n: u, h: dot(u, a) };
}

function frameBound(
  dim: 3 | 4,
  balls: BallSpec[],
  radii: number[],
  centers: number[][],
): { center: number[]; radius: number } {
  const center = new Array<number>(dim).fill(0);
  let reach = 0;
  let lo = Infinity;
  let hi = -Infinity;
  balls.forEach((b, i) => {
    center[1] += b.height / balls.length;
    lo = Math.min(lo, centers[i][1] - radii[i]);
    hi = Math.max(hi, centers[i][1] + radii[i]);
    for (let k = 0; k < dim; k++)
      reach = Math.max(reach, Math.abs(centers[i][k]) + radii[i]);
  });
  reach = Math.max(reach, 3, (hi - lo) * 1.5 + 4);
  return { center, radius: reach };
}

// --------------------------------------------------- maximum vertex balls

/**
 * The maximum vertex balls (the preprint's Def 4.1): per vertex X, the open
 * ball whose boundary passes through X, is orthogonal to every edge there
 * (its centre on the common edge-tangent line — all three edge tangents
 * verified parallel, the ideality check), contains no other vertex, and is
 * maximal — the ball touching the nearest other vertex along its centre
 * line. Side chosen toward the tile interior; a vertex whose ball would be
 * a half-space (the ∞ vertex) yields no seed (the tetra families' case).
 */
function maxVertexBalls(
  faces: SphairahedronFace[],
  vertices: { p: number[]; faces: number[] }[],
  pieces: SphairahedronTilePiece[],
): SphairahedronSeedBall[] {
  const inTile = (p: number[]): boolean => {
    for (const piece of pieces) {
      let d = -Infinity;
      for (const t of piece.terms) d = Math.max(d, termSDF(t, p));
      if (d <= 0) return true;
    }
    return false;
  };
  const faceNormalAt = (f: SphairahedronFace, p: number[]): number[] => {
    if (f.kind === "sphere") {
      const d = dist(p, f.sphere.c);
      return f.sphere.c.map((v, i) => (p[i] - v) / d);
    }
    return [...f.plane.n];
  };
  const seeds: SphairahedronSeedBall[] = [];
  for (const v of vertices) {
    const normals = v.faces.map((fi) => faceNormalAt(faces[fi], v.p));
    const raw = cross3(normals[0], normals[1]);
    const tl = Math.hypot(...raw);
    if (tl < 1e-12) continue;
    const t2 = cross3(normals[0], normals[2]);
    const t2l = Math.hypot(...t2);
    if (t2l < 1e-12) continue;
    if (1 - Math.abs(dot(raw, t2) / (tl * t2l)) > 1e-6) continue;
    const unit = raw.map((x) => x / tl);
    for (const side of [1, -1]) {
      const tangent = unit.map((x) => x * side);
      let tStar = Infinity;
      for (const o of vertices) {
        if (o === v) continue;
        const dy: number[] = o.p.map((x, i) => x - v.p[i]);
        const along = dot(dy, tangent);
        if (along <= 1e-12) continue;
        const t = dot(dy, dy) / (2 * along);
        if (t < tStar) tStar = t;
      }
      if (!Number.isFinite(tStar) || tStar <= 1e-12) continue;
      const c = v.p.map((x, i) => x + tStar * tangent[i]);
      const test = v.p.map((x, i) => x + tangent[i] * tStar * 0.5);
      if (!inTile(test)) continue;
      seeds.push({ c, r: tStar });
      break;
    }
  }
  return seeds;
}

// ----------------------------------------------------- finite construction

/**
 * The finite sphairahedron: every face, tile term, vertex and seed of the
 * infinite scene mapped through the inversion sphere `j`; each image's
 * solid side fixed by mapping the probe (whose image is guaranteed
 * union-interior). The fold order interleaves walls and balls (the
 * reference's gSpheres order). The framing ball becomes the divide plane's
 * image — the quasi-sphere's smooth carrier — grown to hold the dent
 * spheres. Throws when a seed image degenerates to a plane (move J).
 */
function makeFinite(
  scene: BuiltScene,
  j: SphairahedronSphere,
): {
  foldFaces: SphairahedronFoldFace[];
  pieces: SphairahedronTilePiece[];
  probe: number[];
  bound: { center: number[]; radius: number };
  seeds: SphairahedronSeedBall[];
  vertices: SphairahedronVertex[];
} {
  const q0 = invertPoint(j, scene.probe);
  const mapImage = (img: HImage): SphairahedronTerm => {
    if (img.kind === "sphere") {
      const d = dist(q0, img.sphere.c) - img.sphere.r;
      return {
        kind: "sphere",
        c: img.sphere.c,
        r: img.sphere.r,
        inside: d < 0,
      };
    }
    const v = dot(img.plane.n, q0) - img.plane.h;
    return {
      kind: "plane",
      n: [...img.plane.n],
      h: img.plane.h,
      above: v > 0,
    };
  };
  const imageOfFace = (f: SphairahedronFace): HImage =>
    f.kind === "sphere" ? invertSphere(j, f.sphere) : invertPlane(j, f.plane);

  const pieces: SphairahedronTilePiece[] = scene.pieces.map((piece) => ({
    terms: piece.terms.map((t) =>
      t.kind === "sphere"
        ? mapImage(invertSphere(j, { c: t.c, r: t.r }))
        : mapImage(invertPlane(j, { n: t.n, h: t.h })),
    ),
  }));

  // Fold order: walls and balls interleaved (wall0, ball0, wall1, ball1,
  // wall2, ball2 …) when the counts match — the reference's order. Every
  // face's solid side is fixed by q0 (the probe's image lies in the tile):
  // spheres get solidInside = "q0 inside"; planes are re-normalized so the
  // solid side is n·p < h and the fold reflects on the other side.
  const senseOf = (img: HImage): SphairahedronFoldFace => {
    if (img.kind === "sphere") {
      return {
        face: { kind: "sphere", sphere: img.sphere },
        solidInside: dist(q0, img.sphere.c) < img.sphere.r,
      };
    }
    const pl = img.plane;
    if (dot(pl.n, q0) - pl.h > 0) {
      return {
        face: { kind: "plane", plane: { n: pl.n.map((v) => -v), h: -pl.h } },
        solidInside: false,
      };
    }
    return {
      face: { kind: "plane", plane: { n: [...pl.n], h: pl.h } },
      solidInside: false,
    };
  };
  const wallSensed = scene.faces
    .filter((f) => f.kind === "plane")
    .map((f) => senseOf(imageOfFace(f)));
  const ballSensed = scene.faces
    .filter((f) => f.kind === "sphere")
    .map((f) => senseOf(imageOfFace(f)));
  const foldFaces: SphairahedronFoldFace[] = [];
  const nb = ballSensed.length;
  const nw = wallSensed.length;
  for (let k = 0; k < Math.max(nb, nw); k++) {
    if (k < nw) foldFaces.push(wallSensed[k]);
    if (k < nb) foldFaces.push(ballSensed[k]);
  }

  // Framing: the divide plane's image grown to hold the dent spheres.
  const divideImage = invertPlane(j, scene.divide);
  let bound = { center: [...j.c], radius: j.r * 3 };
  if (divideImage.kind === "sphere") {
    const cv = divideImage.sphere.c;
    let radius = divideImage.sphere.r;
    for (const { face } of foldFaces) {
      if (face.kind !== "sphere") continue;
      radius = Math.max(radius, dist(face.sphere.c, cv) + face.sphere.r);
    }
    bound = { center: [...cv], radius: radius * 1.04 };
  }

  const seeds: SphairahedronSeedBall[] = scene.seeds.map((b) => {
    const img = invertSphere(j, b);
    if (img.kind !== "sphere")
      throw new Error("seed ball image degenerate; move the inversion sphere");
    return img.sphere;
  });

  const vertices: SphairahedronVertex[] = scene.vertices.map((v) => ({
    p: invertPoint(j, v.p),
    faces: v.faces,
  }));

  return {
    foldFaces,
    pieces,
    probe: q0,
    bound,
    seeds,
    vertices,
  };
}

// ------------------------------------------------------------ the families

/** The moduli each family reads, its defaults, and its region: per ball, the
 * tangency threshold to the wall the ball does NOT bound (the derived
 * reading of the appendix's boundary curves — module doc). The tetra
 * families have no free moduli and no region; the prism's single threshold
 * on its unpinned ball is Prop 3.12's wall-circle fit (r2 < 1 ⟺ z2² < 6). */
interface SphairahedronFamily {
  dim: 3 | 4;
  label: string;
  reads: readonly ("za" | "zb" | "z2")[];
  defaults: { za?: number; zb?: number; z2?: number };
  balls: (m: { za?: number; zb?: number; z2?: number }) => BallSpec[];
  wallSystem: () => WallSystem;
  divide?: (dim: 3 | 4) => SphairahedronPlane;
  /** Ball name → (untouched wall, radius threshold): the region is every
   * ball STRICTLY clear of its untouched wall; ON the threshold is the
   * admitted boundary. */
  region: Readonly<Record<string, { wall: number; threshold: number }>>;
}

const PI3 = Math.PI / 3;

const FAMILIES: Readonly<Record<SphairahedronFamilyId, SphairahedronFamily>> =
  Object.freeze({
    tetra333: {
      dim: 3,
      label: "tetra 333",
      reads: [],
      defaults: {},
      // The arrows take the moduli record even when the family reads none:
      // a zero-parameter arrow loses the contextual return type and the
      // tuple-typed specs degrade to number[] pairs.
      balls: (_m) => [
        { corner: [0, 1], height: 0, theta: [PI3, PI3], radius: 1, name: "b" },
      ],
      wallSystem: () => wallSystem333(0.5),
      divide: (dim) => ({
        n: [0, 1, 0, 0].slice(0, dim),
        h: 0,
      }),
      region: {},
    },
    tetra4: {
      dim: 4,
      label: "tetra 333 (4D)",
      reads: [],
      defaults: {},
      balls: (_m) => [
        { corner: [0, 1], height: 0, theta: [PI3, PI3], radius: 1, name: "b" },
      ],
      wallSystem: () => wallSystem333(0.5),
      divide: (dim) => ({
        n: [0, 1, 0, 0].slice(0, dim),
        h: 0,
      }),
      region: {},
    },
    prism2: {
      dim: 3,
      label: "prism type 2",
      reads: ["z2"],
      defaults: { z2: 2 },
      balls: (m) => [
        {
          corner: [0, 1],
          height: m.z2 as number,
          theta: [PI3, PI3],
          name: "b2",
        },
        {
          corner: [0, 2],
          height: 0,
          theta: [Math.PI / 6, Math.PI / 2],
          radius: Math.sqrt(3),
          name: "b4",
        },
      ],
      wallSystem: () => wallSystem333(1),
      // Prop 3.12's wall-circle fit: the ball's circle radius on the wall,
      // ρ = r2·sin(π/3), must be below half the wall face width w/2 = √3,
      // which in the ball radius reads r2 < 2 ⟺ z2² < 6 (the open interval
      // (−√6, √6)). The pinned b4's own wall circle spans its whole wall
      // face BY DESIGN (the prism's second vertex) — inherent to the
      // construction, not a boundary.
      region: { b2: { wall: 0, threshold: 2 } },
    },
    cube1: {
      dim: 3,
      label: "cube type 1",
      reads: ["za", "zb"],
      defaults: { za: 0.5, zb: 1.0 },
      balls: (m) => [
        { corner: [0, 1], height: 0, theta: [PI3, PI3], name: "b2" },
        {
          corner: [0, 2],
          height: m.za as number,
          theta: [PI3, PI3],
          name: "b4",
        },
        {
          corner: [1, 2],
          height: m.zb as number,
          theta: [PI3, PI3],
          name: "b6",
        },
      ],
      wallSystem: () => wallSystem333(0.5),
      region: {
        b2: { wall: 2, threshold: 0.75 },
        b4: { wall: 1, threshold: 0.75 },
        b6: { wall: 0, threshold: 0.75 },
      },
    },
    cube4: {
      dim: 3,
      label: "cube type 4",
      reads: ["za", "zb"],
      defaults: { za: 0.4, zb: 0.3 },
      balls: (m) => [
        {
          corner: [0, 1],
          height: 0,
          theta: [Math.PI / 6, PI3],
          name: "b2",
        },
        {
          corner: [0, 2],
          height: m.za as number,
          theta: [PI3, PI3],
          name: "b4",
        },
        {
          corner: [1, 2],
          height: m.zb as number,
          theta: [PI3, Math.PI / 2],
          name: "b6",
        },
      ],
      wallSystem: () => wallSystem236(),
      region: {
        b2: { wall: 2, threshold: 2 * RT3 - 3 },
        b4: { wall: 1, threshold: 4 - 2 * RT3 },
        b6: { wall: 0, threshold: 4 * RT3 - 6 },
      },
    },
    cube9: {
      dim: 3,
      label: "cube type 9",
      reads: ["za", "zb"],
      defaults: { za: 0.3, zb: 0.2 },
      balls: (m) => [
        {
          corner: [0, 1],
          height: 0,
          theta: [Math.PI / 4, Math.PI / 4],
          name: "b2",
        },
        {
          corner: [0, 2],
          height: m.za as number,
          theta: [Math.PI / 2, Math.PI / 4],
          name: "b4",
        },
        {
          corner: [1, 2],
          height: m.zb as number,
          theta: [Math.PI / 4, Math.PI / 2],
          name: "b6",
        },
      ],
      wallSystem: () => wallSystem244(),
      region: {
        b2: { wall: 2, threshold: 0.5 },
        b4: { wall: 1, threshold: 1 / RT2 },
        b6: { wall: 0, threshold: 2 * RT2 - 2 },
      },
    },
  });

function isFamilyId(v: unknown): v is SphairahedronFamilyId {
  return (
    typeof v === "string" &&
    (SPHAIRAHEDRON_FAMILIES as readonly unknown[]).includes(v)
  );
}

/** The dimension an authored block's family names — `3`, `4`, or `null`
 * when the id is not a shipped family (absent, unknown, or not a string).
 * It reads ONLY the family: a block refused for any other reason still
 * names its dimension, so repairing that reason never flips the scene
 * between 3D and 4D. The scene-level dimension derivation is its caller. */
export function sphairahedronAuthoredDimension(
  authored: unknown,
): 3 | 4 | null {
  if (!isPlainObject(authored)) return null;
  const id = authored.family;
  return isFamilyId(id) ? FAMILIES[id].dim : null;
}

// ------------------------------------------------------------ the resolver

export type SphairahedronResolution =
  | {
      ok: true;
      construction: SphairahedronConstruction;
    }
  | { ok: false; reasons: string[] };

/** The region reading of a solved construction: which balls are past their
 * untouched-wall threshold (refusal reasons), which sit ON it (the
 * disclosed boundary). */
function regionRead(
  family: SphairahedronFamily,
  names: readonly string[],
  radii: readonly number[],
): { reasons: string[]; boundary: boolean } {
  const reasons: string[] = [];
  let boundary = false;
  for (let i = 0; i < names.length; i++) {
    const entry = family.region[names[i]];
    if (!entry) continue;
    const r = radii[i];
    const tol =
      SPHAIRAHEDRON_REGION_BOUNDARY_TOL * Math.max(1, entry.threshold);
    if (r > entry.threshold + tol) {
      reasons.push(
        `ball ${names[i]}'s sphere crosses the wall it does not bound ` +
          `(radius ${r.toPrecision(6)} > ${entry.threshold.toPrecision(6)}): ` +
          "outside the family's valid region",
      );
    } else if (Math.abs(r - entry.threshold) <= tol) {
      boundary = true;
    }
  }
  return { reasons, boundary };
}

/**
 * Build the construction for a family at a moduli record — the
 * construction-existence path. Validates only what a construction needs
 * (finite moduli; the region is NOT checked here — the document resolver
 * owns it, and morph intermediates resolve through this path because the
 * region is not convex, module doc). Throws when the construction cannot
 * be built.
 */
export function buildSphairahedron(
  familyId: SphairahedronFamilyId,
  moduli: { za?: number; zb?: number; z2?: number },
  inversion?: { c: readonly number[]; r: number } | null,
): SphairahedronConstruction {
  const family = FAMILIES[familyId];
  const dim = family.dim;
  for (const key of family.reads) {
    const v = moduli[key];
    if (v !== undefined && !isFiniteNumber(v)) {
      throw new Error(`modulus ${key} ${String(v)} is not a finite number`);
    }
  }
  const filled: { za?: number; zb?: number; z2?: number } = {};
  for (const key of family.reads) {
    const v = moduli[key];
    filled[key] = v === undefined ? family.defaults[key] : v;
  }
  const specs = family.balls(filled);
  const { scene } = buildInfinite({
    dim,
    ws: family.wallSystem(),
    balls: specs,
    divide: family.divide?.(dim),
  });
  const names = specs.map((s) => s.name);
  const { boundary } = regionRead(family, names, scene.radii);
  const construction: SphairahedronConstruction = {
    dim,
    family: familyId,
    moduli: filled,
    finite: false,
    inversion: null,
    foldFaces: scene.foldFaces,
    pieces: scene.pieces,
    probe: scene.probe,
    divide: scene.divide,
    bound: scene.bound,
    seeds: scene.seeds,
    vertices: scene.vertices,
    foldCap: scene.foldCap,
    radii: scene.radii,
    ballCenters: scene.ballCenters,
    verification: scene.verification,
    regionBoundary: boundary,
  };
  if (inversion) {
    const fin = makeFinite(scene, inversion);
    return {
      ...construction,
      finite: true,
      inversion: { c: [...inversion.c], r: inversion.r },
      foldFaces: fin.foldFaces,
      pieces: fin.pieces,
      probe: fin.probe,
      bound: fin.bound,
      seeds: fin.seeds,
      vertices: fin.vertices,
    };
  }
  return construction;
}

/**
 * The reflected-reference inversion sphere (the picker's FIRST candidate,
 * module doc): the reference implementation's constrained sphere — the
 * mirror of the last ball through the height axis — with its centre
 * reflected through the divide plane, radius kept. Requires three balls
 * (the cube families); null otherwise. NOT a document default: the finite
 * construction's sphere is authored explicitly — this is the authoring
 * aid the panel child's picker starts from, and the study measured that it
 * alone renders the complement-pocket presentation for many parameters.
 */
export function defaultSphairahedronInversion(
  construction: SphairahedronConstruction,
): { c: number[]; r: number } | null {
  if (construction.ballCenters.length !== 3) return null;
  const last = construction.ballCenters[2];
  const radii = construction.radii;
  const j0 = { c: [-last[0], -last[1], last[2]], r: radii[2] };
  // Reflect the centre through the divide plane.
  const d0 =
    construction.divide.n.reduce((s, v, i) => s + v * j0.c[i], 0) -
    construction.divide.h;
  return {
    c: j0.c.map((v, i) => v - 2 * d0 * construction.divide.n[i]),
    r: j0.r,
  };
}

/**
 * Expand the authored form into an explicit construction (module doc).
 * Absent fields take the family's defaults; present fields out of domain
 * REFUSE with every reason collected, never clamp.
 *
 * Domain: `family` a shipped id; the moduli the family reads finite, and
 * the cube heights non-negative (the published parameter spaces are the
 * non-negative quadrant); the solved radii strictly inside the family's
 * region (every ball clear of the wall it does not bound) with the boundary
 * ADMITTED and disclosed; `inversion` absent = the infinite construction,
 * present = a finite centre (finite numbers; `cw` only on the 4D family)
 * and a positive finite radius — a finite request without a full sphere
 * REFUSES (the sphere is a free parameter; module doc). The construction's
 * own verification problems refuse (a non-positive solved radius, a missing
 * three-ball vertex); its extra wall crossings are inherent to the family
 * geometry (the prism's second vertex) and reported, not refused.
 */
export function resolveSphairahedron(
  authored: SphairahedronAuthored,
): SphairahedronResolution {
  const reasons: string[] = [];
  const block: unknown = authored;
  if (!isPlainObject(block)) {
    return { ok: false, reasons: ["the sphairahedron block is not an object"] };
  }
  const unknownKeys = (o: Record<string, unknown>, known: readonly string[]) =>
    Object.keys(o).filter((key) => !known.includes(key));
  for (const key of unknownKeys(block, SPHAIRAHEDRON_AUTHORED_FIELDS)) {
    reasons.push(`unknown field "${key}" (not readable by this version)`);
  }
  const rawInversion: unknown = block.inversion;
  if (rawInversion !== undefined && !isPlainObject(rawInversion)) {
    reasons.push("inversion is not an object");
  } else if (isPlainObject(rawInversion)) {
    for (const key of unknownKeys(
      rawInversion,
      SPHAIRAHEDRON_INVERSION_FIELDS,
    )) {
      reasons.push(
        `unknown inversion field "${key}" (not readable by this version)`,
      );
    }
  }
  const id = block.family;
  if (id === undefined) {
    reasons.push("no family");
  } else if (!isFamilyId(id)) {
    reasons.push(
      `unknown family ${JSON.stringify(id)} (known: ${SPHAIRAHEDRON_FAMILIES.join(", ")})`,
    );
  }
  const familyId = isFamilyId(id) ? id : null;
  const family = familyId ? FAMILIES[familyId] : null;
  const moduli: { za?: number; zb?: number; z2?: number } = {};
  for (const key of ["za", "zb", "z2"] as const) {
    const v = block[key];
    if (v === undefined) continue;
    if (!isFiniteNumber(v)) {
      reasons.push(
        `modulus ${key} ${JSON.stringify(v)} is not a finite number`,
      );
    } else if (key !== "z2" && v < 0) {
      reasons.push(
        `modulus ${key} ${v} is negative: the family's parameter space is ` +
          "the non-negative quadrant",
      );
    } else {
      moduli[key] = v;
    }
  }
  // The inversion sphere.
  let inversion: { c: number[]; r: number } | null = null;
  let wantFinite = false;
  if (isPlainObject(rawInversion)) {
    wantFinite = true;
    const inv = rawInversion;
    const cx = inv.cx;
    const cy = inv.cy;
    const cz = inv.cz;
    const cw = inv.cw;
    const r = inv.r;
    const hasCenter = cx !== undefined || cy !== undefined || cz !== undefined;
    const hasAny = hasCenter || cw !== undefined || r !== undefined;
    if (hasAny) {
      if (!isFiniteNumber(cx) || !isFiniteNumber(cy) || !isFiniteNumber(cz)) {
        reasons.push("inversion centre cx, cy, cz must all be finite numbers");
      }
      if (!isFiniteNumber(r) || r <= 0) {
        reasons.push("inversion radius r must be a finite positive number");
      }
      if (cw !== undefined) {
        if (!isFiniteNumber(cw)) {
          reasons.push("inversion centre w is not a finite number");
        } else if (family && family.dim === 3 && cw !== 0) {
          reasons.push("inversion centre w applies only to the 4D family");
        }
      }
      if (isFiniteNumber(cx) && isFiniteNumber(cy) && isFiniteNumber(cz)) {
        const c =
          family?.dim === 4
            ? [cx, cy, cz, isFiniteNumber(cw) ? cw : 0]
            : [cx, cy, cz];
        if (isFiniteNumber(r) && r > 0) inversion = { c, r };
      }
    }
    // `{}` (or centre-less) with a valid family: the finite default.
  }
  if (reasons.length > 0 || !family || !familyId) {
    return { ok: false, reasons };
  }

  let construction: SphairahedronConstruction;
  try {
    construction = buildSphairahedron(familyId, moduli, null);
  } catch (e) {
    return { ok: false, reasons: [(e as Error).message] };
  }

  // Verification problems refuse.
  if (construction.verification.problems.length > 0) {
    reasons.push(...construction.verification.problems);
  }

  // The region: strictly inside, boundary admitted and disclosed.
  const names =
    construction.family === "prism2"
      ? ["b2", "b4"]
      : construction.family === "tetra333" || construction.family === "tetra4"
        ? ["b"]
        : ["b2", "b4", "b6"];
  const region = regionRead(
    FAMILIES[construction.family],
    names,
    construction.radii,
  );
  reasons.push(...region.reasons);

  // The finite mapping: the sphere is authored explicitly (module doc).
  if (wantFinite) {
    if (!inversion) {
      reasons.push(
        "a finite construction needs an explicit inversion sphere " +
          "(cx, cy, cz, r): the sphere is a free parameter of the family",
      );
    } else {
      try {
        construction = buildSphairahedron(familyId, moduli, inversion);
      } catch (e) {
        reasons.push((e as Error).message);
      }
    }
  }

  if (reasons.length > 0) return { ok: false, reasons };
  return { ok: true, construction };
}

// -------------------------------------------------------------- analyzer

export type SphairahedronEligibilityStatus =
  "eligible" | "degraded" | "ineligible";

export interface SphairahedronEligibility {
  /** `eligible`: marched at {@link SPHAIRAHEDRON_STEP_SCALE} with no
   * disclosure. `degraded`: still marched, with `degradations` naming what
   * costs (a region-boundary cusp, a capped-fold regime). `ineligible`: no
   * construction exists; see `reasons`. */
  status: SphairahedronEligibilityStatus;
  /** Blockers; non-empty exactly when `ineligible`. */
  reasons: string[];
  /** Disclosures; non-empty exactly when `degraded`. */
  degradations: string[];
}

/**
 * The construction-level gate, in the `analyzeSphereInversionSystem` shape.
 * Ineligible when the vectors or radii are malformed, a solved radius is
 * non-positive, the construction failed its Lemma verification, or the
 * moduli sit past the family's region. Degraded when a moduli pair sits ON
 * a region threshold (the two faces touch tangentially — a cusp the
 * marcher creeps at, the disjoint family's tangency disclosure) or when the
 * fold regime is known to stress (a construction whose balls cross walls
 * they do not bound — legal for the prism's second vertex and the tetra's
 * floor ball, disclosed when it is the region's own edge case).
 */
export function analyzeSphairahedronSystem(
  construction: SphairahedronConstruction,
): SphairahedronEligibility {
  const reasons: string[] = [];
  const degradations: string[] = [];
  const { dim, radii, verification, family } = construction;
  const done = (): SphairahedronEligibility => ({
    status:
      reasons.length > 0
        ? "ineligible"
        : degradations.length > 0
          ? "degraded"
          : "eligible",
    reasons,
    degradations: reasons.length > 0 ? [] : degradations,
  });
  if (dim !== 3 && dim !== 4) {
    reasons.push(`dimension ${String(dim)} is not 3 or 4`);
    return done();
  }
  if (!SPHAIRAHEDRON_FAMILIES.includes(family)) {
    reasons.push(`unknown family "${String(family)}"`);
    return done();
  }
  radii.forEach((r, i) => {
    if (!Number.isFinite(r)) reasons.push(`radius ${i + 1} is not finite`);
    else if (r <= SPHAIRAHEDRON_MIN_RADIUS)
      reasons.push(`radius ${i + 1} is ${r}: not a ball`);
  });
  for (const key of ["za", "zb", "z2"] as const) {
    const v = construction.moduli[key];
    if (v !== undefined && !Number.isFinite(v)) {
      reasons.push(`modulus ${key} is not finite`);
    }
  }
  if (verification.problems.length > 0) {
    reasons.push(...verification.problems);
  }
  reasons.push(
    ...regionRead(FAMILIES[family], ballNames(family), radii).reasons,
  );
  if (reasons.length > 0) return done();
  if (construction.regionBoundary) {
    degradations.push(
      "a ball face is tangent to a wall it does not bound (the moduli sit " +
        "on the region boundary): a cusp the marcher creeps at",
    );
  }
  return done();
}

function ballNames(family: SphairahedronFamilyId): readonly string[] {
  return family === "prism2"
    ? ["b2", "b4"]
    : family === "tetra333" || family === "tetra4"
      ? ["b"]
      : ["b2", "b4", "b6"];
}
